Repository honeycombio/hpsf, pull requests merged in 2025-06, with the labels that each got.

#118 feat: Update logs dedup processor port names
  pkg/data/components/LogDeduplicationProcessor.yaml
Labels: enhancement

#115 fix: make it easier to run smoke tests for templates
  Makefile
Labels: maintenance

#110 feat(components): Added JSON parsing components
  pkg/data/components/ParseAttributeAsJSON.yaml
  pkg/data/components/ParseLogBodyAsJSON.yaml
  pkg/translator/testdata/collector_config/parseattributeasjson_all.yaml
  pkg/translator/testdata/collector_config/parseattributeasjson_defaults.yaml
  pkg/translator/testdata/collector_config/parselogbodyasjson_all.yaml
  pkg/translator/testdata/collector_config/parselogbodyasjson_defaults.yaml
  pkg/translator/testdata/hpsf/parseattributeasjson_all.yaml
  pkg/translator/testdata/hpsf/parseattributeasjson_defaults.yaml
  pkg/translator/testdata/hpsf/parselogbodyasjson_all.yaml
  pkg/translator/testdata/hpsf/parselogbodyasjson_defaults.yaml
  tests/scenario_tests/parseattributeasjson_processor_test.go
  tests/scenario_tests/parselogbodyasjson_processor_test.go
  tests/scenario_tests/testdata/parseattributeasjson_processor_custom.yaml
  tests/scenario_tests/testdata/parseattributeasjson_processor_defaults.yaml
  tests/scenario_tests/testdata/parseattributeasjson_processor_span.yaml
  tests/scenario_tests/testdata/parselogbodyasjson_processor_log_body.yaml
  tests/scenario_tests/testdata/parselogbodyasjson_processor_test.yaml
Labels: enhancement

#108 feat: Update HoneycombExporter to also create collector exporter
  pkg/data/components/HoneycombExporter.yaml
  pkg/data/components/OTelHTTPExporter.yaml
  pkg/data/testdata/HoneycombExporter_output_refinery_config.yaml
  pkg/translator/testdata/collector_config/honeycombexporter_all.yaml
  pkg/translator/testdata/collector_config/honeycombexporter_defaults.yaml
  pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
  pkg/translator/testdata/hpsf/honeycombexporter_defaults.yaml
  pkg/translator/testdata/refinery_config/honeycombexporter_all.yaml
  pkg/translator/testdata/refinery_config/honeycombexporter_defaults.yaml
Labels: enhancement

#123 feat(components): Rename TraceConverter to StartSampling
  examples/hpsfComposedComponents.yaml
  pkg/data/components/StartSampling.yaml
  pkg/data/templates/emathroughput.yaml
  pkg/data/templates/s3.yaml
  pkg/translator/testdata/collector_config/startsampling_all.yaml
  pkg/translator/testdata/collector_config/startsampling_defaults.yaml
  pkg/translator/testdata/hpsf/deterministicsampler_all.yaml
  pkg/translator/testdata/hpsf/deterministicsampler_defaults.yaml
  pkg/translator/testdata/hpsf/emathroughput_all.yaml
  pkg/translator/testdata/hpsf/emathroughput_defaults.yaml
  pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
  pkg/translator/testdata/hpsf/honeycombexporter_defaults.yaml
  pkg/translator/testdata/hpsf/keeperrors_all.yaml
  pkg/translator/testdata/hpsf/keeperrors_defaults.yaml
  pkg/translator/testdata/hpsf/samplebyhttpstatus_all.yaml
  pkg/translator/testdata/hpsf/samplebyhttpstatus_defaults.yaml
  pkg/translator/testdata/hpsf/samplebytraceduration_all.yaml
  pkg/translator/testdata/hpsf/samplebytraceduration_defaults.yaml
  pkg/translator/testdata/hpsf/startsampling_all.yaml
  pkg/translator/testdata/hpsf/startsampling_defaults.yaml
  tests/scenario_tests/keep_errors_test.go
  tests/scenario_tests/testdata/keep_errors.yaml
Labels: enhancement

#125 feat: move dev component to alpha
  pkg/data/components/FilterLogsBySeverityProcessor.yaml
  pkg/data/components/ParseAttributeAsJSON.yaml
  pkg/data/components/ParseLogBodyAsJSON.yaml
Labels: enhancement

#130 feat: Add subtype labels for bool properties
  pkg/data/components/HoneycombExporter.yaml
  pkg/data/components/OTelGRPCExporter.yaml
  pkg/data/components/OTelHTTPExporter.yaml
  pkg/data/components/StartSampling.yaml
Labels: enhancement

#137 fix: Update redaction component tests logs pipeline names
  pkg/translator/testdata/collector_config/redactionprocessor_all.yaml
  pkg/translator/testdata/collector_config/redactionprocessor_defaults.yaml
Labels: bug

#138 fix: Update StartSampling UseTLS label
  pkg/data/components/StartSampling.yaml
Labels: bug

#139 feat: Add APIPort parameter to HoneycombExporter
  pkg/data/components/HoneycombExporter.yaml
  pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
Labels: enhancement

#109 feat: Add Symbolicator component
  pkg/data/components/SymbolicatorProcessor.yaml
  pkg/translator/testdata/collector_config/symbolicatorprocessor_all.yaml
  pkg/translator/testdata/collector_config/symbolicatorprocessor_defaults.yaml
  pkg/translator/testdata/hpsf/symbolicatorprocessor_all.yaml
  pkg/translator/testdata/hpsf/symbolicatorprocessor_defaults.yaml
Labels: enhancement

#146 rel: Prepare 0.9.0 release
  CHANGELOG.md
  version.go
Labels: maintenance

#148 feat: More sophisticated validations for hpsf
  pkg/config/helpers.go
  pkg/config/templateComponent.go
  pkg/config/templateProperty.go
  pkg/data/components/HoneycombExporter.yaml
  pkg/data/components/OTelGRPCExporter.yaml
  pkg/data/components/OTelHTTPExporter.yaml
  pkg/data/components/OTelReceiver.yaml
  pkg/hpsf/hpsfTypes_test.go
  pkg/hpsf/hpsfValidations.go
  pkg/translator/testdata/bad_hpsf/README.md
  pkg/translator/testdata/bad_hpsf/dup_names.yaml
  pkg/translator/testdata/bad_hpsf/missing_comp.yaml
  pkg/translator/testdata/bad_hpsf/missing_port.yaml
  pkg/translator/testdata/bad_hpsf/missing_property.yaml
  pkg/translator/testdata/bad_hpsf/missing_startsampling.yaml
  pkg/translator/testdata/bad_hpsf/multiple_sample_paths.yaml
  pkg/translator/testdata/collector_config/default.yaml
  pkg/translator/testdata/collector_config/filterlogbyseverity_all.yaml
  pkg/translator/testdata/collector_config/filterlogbyseverity_defaults.yaml
  pkg/translator/testdata/collector_config/filterprocessor_all.yaml
  pkg/translator/testdata/collector_config/filterprocessor_defaults.yaml
  pkg/translator/testdata/collector_config/honeycombexporter_all.yaml
  pkg/translator/testdata/collector_config/honeycombexporter_defaults.yaml
  pkg/translator/testdata/collector_config/logdeduplicationprocessor_all.yaml
  pkg/translator/testdata/collector_config/logdeduplicationprocessor_defaults.yaml
  pkg/translator/testdata/collector_config/nopreceiver_all.yaml
  pkg/translator/testdata/collector_config/nopreceiver_defaults.yaml
  pkg/translator/testdata/collector_config/otelgrpcexporter_defaults.yaml
  pkg/translator/testdata/collector_config/otelhttpexporter_defaults.yaml
  pkg/translator/testdata/collector_config/otelreceiver_all.yaml
  pkg/translator/testdata/collector_config/otelreceiver_defaults.yaml
  pkg/translator/testdata/collector_config/parseattributeasjson_all.yaml
  pkg/translator/testdata/collector_config/parseattributeasjson_defaults.yaml
  pkg/translator/testdata/collector_config/parselogbodyasjson_all.yaml
  pkg/translator/testdata/collector_config/parselogbodyasjson_defaults.yaml
  pkg/translator/testdata/collector_config/redactionprocessor_all.yaml
  pkg/translator/testdata/collector_config/redactionprocessor_defaults.yaml
  pkg/translator/testdata/collector_config/startsampling_all.yaml
  pkg/translator/testdata/collector_config/symbolicatorprocessor_all.yaml
  pkg/translator/testdata/collector_config/symbolicatorprocessor_defaults.yaml
  pkg/translator/testdata/hpsf/honeycombexporter_all.yaml
  pkg/translator/testdata/hpsf/honeycombexporter_defaults.yaml
  pkg/translator/testdata/hpsf/startsampling_all.yaml
  pkg/translator/testdata/hpsf/startsampling_defaults.yaml
  pkg/translator/testdata/refinery_config/honeycombexporter_all.yaml
  pkg/translator/translator.go
  pkg/translator/translator_test.go
Labels: enhancement

#147 fix: Remove environment property from samplers
  examples/hpsf.yaml
  examples/hpsf2.yaml
  pkg/data/components/DeterministicSampler.yaml
  pkg/data/components/EmaThroughput.yaml
  pkg/data/components/KeepErrors.yaml
  pkg/data/components/SampleByHTTPStatus.yaml
  pkg/data/components/SampleByTraceDuration.yaml
  pkg/data/testdata/DeterministicSampler_output_refinery_rules.yaml
  pkg/data/testdata/EmaThroughput_output_refinery_rules.yaml
  pkg/translator/testdata/bad_hpsf/missing_port.yaml
  pkg/translator/testdata/hpsf/deterministicsampler_all.yaml
  pkg/translator/testdata/hpsf/emathroughput_all.yaml
  pkg/translator/testdata/hpsf/keeperrors_all.yaml
  pkg/translator/testdata/hpsf/samplebyhttpstatus_all.yaml
  pkg/translator/testdata/hpsf/samplebytraceduration_all.yaml
  pkg/translator/testdata/refinery_rules/deterministicsampler_all.yaml
  pkg/translator/testdata/refinery_rules/emathroughput_all.yaml
  pkg/translator/testdata/refinery_rules/keeperrors_all.yaml
  pkg/translator/testdata/refinery_rules/samplebyhttpstatus_all.yaml
  pkg/translator/testdata/refinery_rules/samplebytraceduration_all.yaml
  tests/scenario_tests/keep_errors_test.go
  tests/scenario_tests/testdata/keep_errors.yaml
Labels: bug
