Repository honeycombio/hpsf, pull requests merged in 2025-02, with the labels that each got.

#23 fix: DeterministicSampler component template update
  pkg/config/components/deterministicSampler.yaml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/hpsf/hpsfTypes.go
  pkg/hpsf/hpsfTypes_test.go
  pkg/translator/testdata/default_collector_config.yaml
  pkg/translator/testdata/default_refinery_config.yaml
  pkg/translator/testdata/default_refinery_rules.yaml
  pkg/translator/translator_test.go
Labels: bug

#26 fix: Fix encoding of map to handle nesting
  pkg/config/components/FilterProcessor.yaml
  pkg/config/helpers.go
  pkg/config/templateComponent.go
Labels: enhancement

#29 maint: add make targets for validating configs
  .gitignore
  Makefile
  testTemplate.sh
Labels: documentation
